import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// Config
import { useState } from 'react'
import { appName } from '@/config/constants/app'

// Component
import Navbar from '@/components/Navbar'

// MUI
import Box from '@mui/material/Box'

const Home: NextPage = () => {
  const [state, setState] = useState(false)
  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null)

  const onClick = () => {
    setState(true)
  }

  const open = Boolean(anchorEl)

  const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    setAnchorEl(event.currentTarget)
  }

  return (
    <div>
      <Head>
        <title>{appName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Box component="main">
        <main className={styles.main}>
          <h1 className={styles.title}>
            Comming Soon...
          </h1>
        </main>
      </Box>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          © 2022 Dustb0x.
        </a>
      </footer>
    </div>
  )
}

export default Home
