// Config
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { appName } from '@/config/constants/app'

// Component
import Navbar from '@/components/Navbar'

// MUI
import Box from '@mui/material/Box'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>{appName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Box component="main">
        <main className={styles.main}>
          <h1 className={styles.title}>
            Comming Soon...
          </h1>
        </main>
      </Box>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          © 2022 {appName}.
        </a>
      </footer>
    </div>
  )
}

export default Home
